### ISSUE TITLE
Integrate keycloak authentication

### ISSUE THREAD

**Issue by kylim32** [hsa-projects/subject-registration-frontend#20]
Description
---

- [x] **Solve bug: `subjectSelection is null` when opening the subject overview 

Integrate keycloak authentication so that students can login to the site. 

Requirements:

- Backend-branch: `feat-registration` (new: `dev`)
- Docker to start the keycloak server
- Uni VPN setup (only when using the HSA realm)
- Postman [optional] (to dispatch HTTP requests)

How-to Links:
---

https://scalac.io/blog/user-authentication-keycloak-1/

https://medium.com/devops-dudes/secure-front-end-react-js-and-back-end-node-js-express-rest-api-with-keycloak-daf159f0a94e

**Keycloak: Dummy realm credentials and settings:**
---
- Admin username: admin
- Admin password: Pa55w0rd
- Dummy user - username: john
- Dummy user - password: john

**Realm settings:**

- must be public! see https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter
- `One important thing to note about using client-side applications is that the client has to be a public client as there is no secure way to store client credentials in a client-side application. This makes it very important to make sure the redirect URIs you have configured for the client are correct and as specific as possible.`

- Set Accept-Types to `*`

**Keycloak with PostgreSQL backend as docker-compse file:**

```yml
version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres
```

- configure with `sudo docker-compose up`
- start with `sudo docker-compose start`
- stop with `sudo docker-compose stop`
- delete containers with `sudo docker-compose down`
- view all docker processes: `sudo docker ps`

Backend dev notes:
---

![image](https://user-images.githubusercontent.com/83591066/126155367-7f91b446-a0b7-49be-877f-546804e39055.png)

![image](https://user-images.githubusercontent.com/83591066/126185792-863464f2-c0c0-4049-af05-c5ac90cd7199.png)
